"""The export renderers.

Acceptance test 1 is byte-identical output against the legacy renderer; that
comparison lives in `test_parity.py` where the legacy module is available.
These are the properties worth pinning down without it.
"""

from datetime import date

from structura.stores.markdown import MarkdownStore
from structura.views import render

TODAY = date(2026, 8, 31)


def _docs(workspace):
    return MarkdownStore(workspace).documents()


def test_the_banner_names_its_generator(workspace):
    out = render.render_open_items(_docs(workspace), TODAY, generator="structura")
    assert "<!-- GENERATED BY structura — do not edit." in out
    assert out.startswith("---\ntype: index\ntitle: Open Items\ndate: 2026-08-31\n---\n")


def test_the_default_generator_is_the_legacy_one(workspace):
    """Parity is measured against files that name the legacy script, so the
    default has to keep naming it until that tool is retired."""
    out = render.render_assets(_docs(workspace), TODAY)
    assert render.LEGACY_GENERATOR in out


def test_open_items_group_by_the_area_of_the_asset_not_the_source(workspace):
    """R33: the standup carries `area: wwt`, but its open task names an asset
    in `paint`. Grouping by the source note files the work where it happened to
    be written down rather than where the equipment is."""
    out = render.render_open_items(_docs(workspace), TODAY)
    assert "## paint" in out
    assert "## wwt" not in out


def test_done_tasks_are_not_in_the_open_register(workspace):
    out = render.render_open_items(_docs(workspace), TODAY)
    assert "Diagnose riser" in out
    assert "Old work" not in out


def test_age_is_computed_from_today(workspace):
    out = render.render_open_items(_docs(workspace), TODAY)
    assert f"| {(TODAY - date(2026, 6, 1)).days}d |" in out


def test_an_empty_workspace_says_so(tmp_path):
    docs = MarkdownStore(tmp_path).documents()
    assert render.render_open_items(docs, TODAY).endswith("No open items.\n")
    assert render.render_assets(docs, TODAY).endswith("No asset notes yet.\n")
    assert render.render_contacts(docs, TODAY).endswith("No person or organisation notes yet.\n")
    assert render.render_placeholders(docs, TODAY).endswith(
        "No placeholders — every wikilink resolves to a note.\n"
    )


def test_a_pipe_in_a_value_cannot_corrupt_the_table(tmp_path, write_note):
    write_note(
        tmp_path,
        "Obs.md",
        dtype="observation",
        area="paint",
        body="- [ ] #item Check a|b [[X]] owner:[[Y]] raised:2026-06-01\n",
    )
    out = render.render_open_items(MarkdownStore(tmp_path).documents(), TODAY)
    row = next(line for line in out.splitlines() if "Check" in line)
    assert "Check a\\|b" in row
    assert row.count("|") - row.count("\\|") == 8


def test_the_asset_tree_nests_by_part_of(workspace):
    out = render.render_assets(_docs(workspace), TODAY)
    lines = [line for line in out.splitlines() if line.strip().startswith("- [[")]
    assert lines[0].startswith("- [[Paint Line]]")
    assert lines[1].startswith("  - [[Post Rinse 4]]")


def test_an_asset_in_a_part_of_cycle_is_reported_not_dropped(tmp_path, write_note):
    """Every node in a cycle has an ancestor inside the cycle, so none is
    reachable from a root. Without the unreachable pass they vanish silently."""
    write_note(tmp_path, "A.md", dtype="asset", area="paint", body="Part of [[B]]\n")
    write_note(tmp_path, "B.md", dtype="asset", area="paint", body="Part of [[A]]\n")

    out = render.render_assets(MarkdownStore(tmp_path).documents(), TODAY)
    assert "## Unreachable (cycle in Part of)" in out
    assert "- [[A]] — declared parent: [[B]]" in out
    assert "- [[B]] — declared parent: [[A]]" in out


def test_a_person_is_listed_under_every_org_they_belong_to(tmp_path, write_note):
    write_note(tmp_path, "Acme.md", dtype="org", org_type="internal")
    write_note(tmp_path, "Maintenance.md", dtype="org", org_type="internal")
    write_note(
        tmp_path,
        "Dana.md",
        dtype="person",
        organization="Acme",
        body="Part of [[Maintenance]]\n",
    )

    out = render.render_contacts(MarkdownStore(tmp_path).documents(), TODAY)
    acme = out.index("## [[Acme]]")
    maintenance = out.index("## [[Maintenance]]")
    assert out.count("[[Dana]]") == 2
    assert "Also in" in out
    assert acme < maintenance


def test_a_disagreeing_employer_is_reported_rather_than_resolved_silently(tmp_path, write_note):
    write_note(
        tmp_path,
        "Dana.md",
        dtype="person",
        organization="Acme",
        body="Works at [[Other Co]]\n",
    )
    out = render.render_contacts(MarkdownStore(tmp_path).documents(), TODAY)
    assert "## Conflicting employer" in out
    assert "| [[Dana]] | Acme | [[Other Co]] |" in out


def test_placeholders_are_ranked_and_attributed(workspace):
    out = render.render_placeholders(
        _docs(workspace), TODAY, frozenset(MarkdownStore(workspace).link_target_names())
    )
    assert "| 2 | Maintenance | [[Standup]] |" in out
    assert "| 1 | Missing | [[Alpha]] |" in out
