"""Export renderers: the generated registers, reproduced byte for byte.

Ported from the legacy `render` module. Acceptance test 1 is that Structura's
export is byte-identical to the legacy output for the same workspace, so this
is a translation of call shapes and nothing else -- every rule, every em dash,
every pluralisation, and every ruling comment (R20, R21, R31, R33) came across
intact.

One thing is parameterised rather than frozen: the generator named in the
banner. It still defaults to the legacy script, because parity is measured
against files that name it. When the legacy tool is retired, that default
changes in one place and the parity baseline changes with it.

Every function is pure and takes `today` explicitly where dates matter, so the
output is deterministic under test.
"""

from __future__ import annotations

import re
from collections import Counter, defaultdict
from datetime import date

from structura.core.document import Document
from structura.core.links import strip_section
from structura.stores.markdown import build_alias_map

LEGACY_GENERATOR = ".foam/scripts/reindex.py"

BANNER = (
    "---\ntype: index\ntitle: {title}\ndate: {today}\n---\n\n"
    "<!-- GENERATED BY {generator} — do not edit. Changes will be overwritten. -->\n\n"
    "# {title}\n\n"
)

# The body line that carries a person's employer, mirroring the parser's
# PARENT_RE for assets. Scanned instead of the document's whole link list
# because a person note may legitimately link an org it is not employed by --
# a vendor named in a note about a call, say -- and counting those as
# employers would file the person under the wrong heading.
WORKS_AT_RE = re.compile(r"^\s*Works at\s+\[\[([^\]]+)\]\]", re.MULTILINE)


def _banner(title: str, today: date, generator: str) -> str:
    return BANNER.format(title=title, today=today.isoformat(), generator=generator)


def _plural(count: int, noun: str) -> str:
    """`1 observation`, `0 observations`, `2 observations`."""
    return f"{count} {noun}" if count == 1 else f"{count} {noun}s"


def _escape_cell(value: str) -> str:
    """Escape the pipe character so a value can't corrupt a markdown table's
    column structure when interpolated into a cell."""
    return str(value).replace("|", "\\|")


def render_open_items(
    documents: list[Document], today: date, generator: str = LEGACY_GENERATOR
) -> str:
    """Open items grouped by the AREA OF THE ASSET the item names (R33).

    Grouping by the source note's `area` files an item wherever it happens to
    be written down rather than where the work is. `1-Projects/Paint Line.md`
    carries `area: paint`, so its "Long-horizon WWT elimination project" item
    landed under `## paint` and its two `[[Power & Free]]` items with it.
    Anyone reading the `wwt` group to see everything open on waste water would
    have missed the elimination project entirely, and nothing on the row said
    so -- the misfiling is invisible without cross-checking every row against
    its asset.

    The asset name is resolved through the alias map first, so an item written
    against `[[WWT]]` groups with one written against
    `[[Waste Water Treatment]]`.

    Fallback to the source note's `area` covers every case where the asset
    cannot supply one: no asset link at all, an asset that names no note in
    this workspace (a placeholder), or an asset note with no `area` key. The
    note's own area is the best remaining evidence in all three.
    """
    out = _banner("Open Items", today, generator)

    alias_map = build_alias_map(documents)
    area_by_title = {
        doc.title: str(doc.fields["area"]) for doc in documents if doc.fields.get("area")
    }

    by_area: dict[str, list] = defaultdict(list)
    for doc in documents:
        note_area = str(doc.fields.get("area", "unassigned"))
        for task in doc.tasks:
            if task.done:
                continue
            asset_area = None
            if task.asset:
                asset_area = area_by_title.get(alias_map.get(task.asset, task.asset))
            by_area[asset_area or note_area].append(task)

    if not any(by_area.values()):
        return out + "No open items.\n"

    for area in sorted(by_area):
        tasks = sorted(
            by_area[area],
            key=lambda t: (t.raised is None, t.raised or date.max),
        )
        out += f"## {area}\n\n"
        out += "| Age | Item | Asset | Owner | Raised | Due | Source |\n"
        out += "| ---: | --- | --- | --- | --- | --- | --- |\n"
        for task in tasks:
            age = f"{(today - task.raised).days}d" if task.raised else "—"
            asset = f"[[{_escape_cell(task.asset)}]]" if task.asset else "—"
            owner = f"[[{_escape_cell(task.owner)}]]" if task.owner else "—"
            raised = task.raised.isoformat() if task.raised else "—"
            # `due:` is optional, so most rows carry an em dash here. It is
            # rendered plain, exactly like `raised:` -- no overdue marker,
            # because Age already carries the urgency signal, and marking
            # overdue would need a rule for the many items that never had a
            # due date at all.
            due = task.due.isoformat() if task.due else "—"
            description = _escape_cell(task.description)
            source = _escape_cell(task.source)
            out += (
                f"| {age} | {description} | {asset} | {owner} | {raised} | {due} | [[{source}]] |\n"
            )
        out += "\n"

    return out


def render_assets(documents: list[Document], today: date, generator: str = LEGACY_GENERATOR) -> str:
    out = _banner("Assets", today, generator)

    assets = [d for d in documents if d.dtype == "asset"]
    if not assets:
        return out + "No asset notes yet.\n"

    alias_map = build_alias_map(documents)

    open_items: Counter[str] = Counter()
    mentions: Counter[str] = Counter()
    for doc in documents:
        for task in doc.tasks:
            if task.asset and not task.done:
                open_items[alias_map.get(task.asset, task.asset)] += 1
        if doc.dtype == "observation":
            # Count distinct assets linked from this note, not link
            # occurrences -- a note that links the same asset three times
            # (e.g. once in **Assets:** and twice more in item lines) is one
            # observation of that asset, not three (R20).
            linked_assets = {
                alias_map.get(strip_section(link), strip_section(link)) for link in doc.link_targets
            }
            for asset in linked_assets:
                mentions[asset] += 1

    # An asset may declare more than one parent (e.g. a component shared by two
    # machines), so it is filed under every resolved parent, not just one -- it
    # will then be printed once per parent branch below, which is the correct
    # picture of a DAG rather than a strict tree.
    children: dict[str | None, list[Document]] = defaultdict(list)
    for asset in assets:
        parents = [alias_map.get(p, p) for p in asset.parents] or [None]
        for parent in parents:
            children[parent].append(asset)

    titles = {a.title for a in assets}
    by_title = {a.title: a for a in assets}
    emitted: set[str] = set()

    def emit(parent: str | None, depth: int) -> str:
        block = ""
        for asset in sorted(children.get(parent, []), key=lambda a: a.title):
            emitted.add(asset.title)
            status = asset.fields.get("status", "—")
            block += (
                f"{'  ' * depth}- [[{asset.title}]] — {status} · "
                f"{open_items[asset.title]} open · "
                f"{_plural(mentions[asset.title], 'observation')}\n"
            )
            block += emit(asset.title, depth + 1)
        return block

    out += emit(None, 0)

    # Assets whose declared parent is not itself an asset note would otherwise
    # be dropped from the tree entirely.
    orphaned = [p for p in children if p is not None and p not in titles]
    if orphaned:
        out += "\n## Unresolved parents\n\n"
        for parent in sorted(orphaned):
            out += f"- `{parent}` referenced as a parent but has no asset note\n"
            out += emit(parent, 1)

    # Assets whose Part of chain forms a cycle have a parent that IS a real
    # asset note, so they never fall into "Unresolved parents" -- but every
    # node in the cycle also has an ancestor that's a member of the cycle, so
    # none of them is ever reachable from a None root either. Without this,
    # they would vanish from the tree silently. Detected here as: never
    # emitted by the walks above.
    unreachable = sorted(t for t in titles if t not in emitted)
    if unreachable:
        out += "\n## Unreachable (cycle in Part of)\n\n"
        for title in unreachable:
            asset = by_title[title]
            parents = [alias_map.get(p, p) for p in asset.parents] or ["—"]
            declared = " · ".join(f"[[{p}]]" for p in parents)
            out += f"- [[{title}]] — declared parent: {declared}\n"

    return out


def _declared_org(person: Document) -> str | None:
    """The `organization:` scalar on a person note, or None if absent/blank."""
    declared = str(person.fields.get("organization") or "").strip()
    return declared or None


def _linked_org(person: Document) -> str | None:
    """The org named by the person note's `Works at [[...]]` body line."""
    match = WORKS_AT_RE.search(person.live_text)
    return strip_section(match.group(1)) if match else None


def _member_orgs(person: Document) -> list[str]:
    """Orgs named by the person note's `Part of [[Org]]` lines, in order.

    `Part of` is the workspace's existing word for "belongs to a larger
    thing", and the parser already collects every one of them on every
    document -- not only on assets -- so a person's departments need no new
    grammar and no parser change. Reusing it also inherits the rule the asset
    tree already follows: a document may declare more than one parent, and it
    is filed under every one rather than only the first.
    """
    return [strip_section(parent) for parent in person.parents]


def org_affiliations(person: Document, alias_map: dict[str, str]) -> list[str]:
    """Every org a person belongs to, canonical and deduped, primary first.

    A person is not employed by one org and nothing else. Someone can draw a
    Schneider Electric paycheque and be the person you call about Maintenance
    at the same time, and a contact page that files them under only one of
    those cannot answer "who is on Maintenance" -- the question it exists to
    answer.

    The primary affiliation is the employer: the `organization:` scalar, or the
    `Works at [[Org]]` line when the scalar is absent. Every `Part of [[Org]]`
    line adds another. Order is declaration order so the employer leads, and
    duplicates collapse, so naming the same org in both `organization:` and a
    `Part of` line lists the person once rather than twice under one heading.
    """

    def resolve(name: str | None) -> str | None:
        return alias_map.get(name, name) if name else None

    ordered = [resolve(_declared_org(person)) or resolve(_linked_org(person))]
    ordered += [resolve(org) for org in _member_orgs(person)]

    affiliations: list[str] = []
    for name in ordered:
        if name and name not in affiliations:
            affiliations.append(name)
    return affiliations


def render_contacts(
    documents: list[Document], today: date, generator: str = LEGACY_GENERATOR
) -> str:
    """People grouped by the organisations they belong to.

    A person can belong to more than one org at once -- a Maintenance Manager
    is on Maintenance and employed by Schneider Electric, both at the same time
    -- so a person is listed under every org they name, the way an asset with
    two parents is listed under both. Filing each person under a single org
    would make "who is on Maintenance" unanswerable from the page whose job is
    answering it.

    A person note names its employer twice: once as the `organization:`
    frontmatter scalar and once as the `Works at [[Org]]` body line. Both are
    legitimate -- the scalar is not a wikilink, so it does not trip rule 2, and
    the body link is what earns the org its backlink -- but they can disagree,
    and only one of them can be the primary affiliation.

    The scalar wins, because it is the key the person template prompts for and
    the one every person note carries. The body link is the fallback when the
    scalar is absent, so a note that records the employer only as a link is
    still filed rather than dropped into Unaffiliated.

    A disagreement between the two is never resolved silently: filing under one
    and saying nothing would put a person under the wrong org with nothing on
    the page admitting it -- the same class of invisible misfiling R33 removed
    from the open-item register. Every conflict is listed at the foot of the
    page with both candidates. `Part of` lines never conflict with anything:
    they are additional, not alternative.

    Only the `Works at` line is read for the employer, never the note's whole
    link list: a person note may legitimately link an org it does not work for
    (a vendor named in the record of a call), and treating that as an employer
    would file the person under the wrong heading for the same silent reason. A
    department is therefore explicit -- a `Part of` line -- rather than inferred
    from any link that happens to be present.

    Orgs with no contacts recorded are still given a section. An empty section
    is the visible form of a gap worth filling; omitting the org entirely would
    make an org with no contacts indistinguishable from one that does not
    exist.
    """
    out = _banner("Contacts", today, generator)

    people = [d for d in documents if d.dtype == "person"]
    orgs = {d.title: d for d in documents if d.dtype == "org"}
    if not people and not orgs:
        return out + "No person or organisation notes yet.\n"

    alias_map = build_alias_map(documents)
    all_titles = {doc.title for doc in documents}

    def resolve(name: str | None) -> str | None:
        return alias_map.get(name, name) if name else None

    # Each entry is (person, every org they belong to), so a row can name the
    # person's OTHER orgs without recomputing them per section.
    by_org: dict[str | None, list[tuple[Document, list[str]]]] = defaultdict(list)
    conflicts: list[tuple[Document, str, str]] = []
    for person in people:
        declared = resolve(_declared_org(person))
        linked = resolve(_linked_org(person))
        if declared and linked and declared != linked:
            conflicts.append((person, declared, linked))

        affiliations = org_affiliations(person, alias_map)
        if not affiliations:
            by_org[None].append((person, affiliations))
        for org in affiliations:
            by_org[org].append((person, affiliations))

    # Every org note gets a heading even with no one filed under it.
    for title in orgs:
        by_org.setdefault(title, [])

    # A column of nothing but em dashes is noise. It earns its place only once
    # someone is actually cross-listed, which is also the only time a reader
    # needs telling that a repeated name is one person in two orgs rather than
    # a duplicated row.
    cross_listed = any(
        len(affiliations) > 1 for entries in by_org.values() for _, affiliations in entries
    )

    named = sorted(title for title in by_org if title is not None)
    # None -- people with no employer and no `Part of` line -- sorts last,
    # after every named org, because it is the leftovers group.
    groups = named + ([None] if None in by_org else [])

    for title in groups:
        entries = sorted(
            by_org[title],
            key=lambda entry: (
                str(entry[0].fields.get("last_name") or entry[0].title).lower(),
                str(entry[0].fields.get("first_name") or "").lower(),
                entry[0].title.lower(),
            ),
        )
        count = _plural(len(entries), "contact")
        if title is None:
            out += f"## Unaffiliated — {count}\n\n"
            out += (
                "Person notes with no `organization:` key, no "
                "`Works at [[Org]]` line and no `Part of [[Org]]` line.\n\n"
            )
        else:
            org = orgs.get(title)
            # Three different gaps that must not look alike: a written org, an
            # org named by a person note but never written (a placeholder, the
            # org-level form of an unwritten note), and a `Part of` line
            # pointing at a note that exists but is not an org at all -- an
            # asset, say, which is a modelling error rather than a missing note.
            if org:
                kind = str(org.fields.get("org_type") or "—")
            elif title in all_titles:
                kind = "not an org note"
            else:
                kind = "no org note"
            out += f"## [[{_escape_cell(title)}]] — {kind} · {count}\n\n"

        if not entries:
            out += "No contacts recorded.\n\n"
            continue

        header = "| Name | Role | Category | Email | Phone |"
        divider = "| --- | --- | --- | --- | --- |"
        if cross_listed:
            header += " Also in |"
            divider += " --- |"
        out += f"{header}\n{divider}\n"

        for person, affiliations in entries:
            role = _escape_cell(person.fields.get("role") or "—")
            category = _escape_cell(person.fields.get("category") or "—")
            email = _escape_cell(person.fields.get("email") or "—")
            phone = _escape_cell(person.fields.get("phone") or "—")
            row = f"| [[{_escape_cell(person.title)}]] | {role} | {category} | {email} | {phone} |"
            if cross_listed:
                others = [org for org in affiliations if org != title]
                also = " · ".join(f"[[{_escape_cell(o)}]]" for o in others) or "—"
                row += f" {also} |"
            out += row + "\n"
        out += "\n"

    if conflicts:
        out += "## Conflicting employer\n\n"
        out += (
            "These notes name one employer in `organization:` and another in "
            "`Works at [[Org]]`. Filed under the frontmatter value; fix the "
            "note to remove the ambiguity. A `Part of [[Org]]` line is not a "
            "conflict -- it adds an org rather than replacing one.\n\n"
        )
        out += "| Person | organization: | Works at |\n"
        out += "| --- | --- | --- |\n"
        for person, declared, linked in sorted(conflicts, key=lambda c: c[0].title):
            out += (
                f"| [[{_escape_cell(person.title)}]] | {_escape_cell(declared)} "
                f"| [[{_escape_cell(linked)}]] |\n"
            )
        out += "\n"

    return out


def render_placeholders(
    documents: list[Document],
    today: date,
    existing_files: frozenset[str] = frozenset(),
    generator: str = LEGACY_GENERATOR,
) -> str:
    out = _banner("Placeholders", today, generator)

    alias_map = build_alias_map(documents)
    # existing_files (R21) covers on-disk targets such as
    # [[dry-poster-min.pdf]] -- a non-markdown file must be linked by its full
    # filename, extension included, or it stays a placeholder (R31) -- so those
    # don't get reported as unwritten notes.
    existing = set(alias_map) | set(existing_files)

    counts: Counter[str] = Counter()
    sources: dict[str, set[str]] = defaultdict(set)
    for doc in documents:
        for link in doc.link_targets:
            target = strip_section(link)
            if target and target not in existing:
                counts[target] += 1
                sources[target].add(doc.title)

    if not counts:
        return out + "No placeholders — every wikilink resolves to a note.\n"

    out += "Unwritten notes, ranked by inbound links. Promote from the top.\n\n"
    out += "| Inbound | Placeholder | Referenced by |\n"
    out += "| ---: | --- | --- |\n"
    for target, count in counts.most_common():
        refs = ", ".join(f"[[{_escape_cell(s)}]]" for s in sorted(sources[target]))
        out += f"| {count} | {_escape_cell(target)} | {refs} |\n"

    return out
